# Generated by Django 6.0.7 on 2026-08-04 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='avg_budget_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('hill_station', 'Hill Station'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('adventure', 'Adventure'), ('pilgrimage', 'Pilgrimage'), ('city', 'City')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(choices=[('rajasthan', 'Rajasthan'), ('kerala', 'Kerala'), ('goa', 'Goa'), ('himachal_pradesh', 'Himachal Pradesh'), ('uttarakhand', 'Uttarakhand'), ('tamil_nadu', 'Tamil Nadu'), ('maharashtra', 'Maharashtra'), ('jammu_kashmir', 'Jammu & Kashmir')], max_length=30),
        ),
    ]
