# Generated by Django 6.0.7 on 2026-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_options_remove_destination_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach'), ('hill_station', 'Hill Station'), ('heritage', 'Heritage'), ('wildlife', 'Wildlife'), ('adventure', 'Adventure'), ('pilgrimage', 'Pilgrimage'), ('city', 'City'), ('Waterfall', 'waterfall'), ('historical', 'historical')], max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Maharashtra', 'Maharashtra'), ('Rajasthan', 'Rajasthan'), ('Kerala', 'Kerala'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Gujarat', 'Gujarat'), ('West Bengal', 'West Bengal'), ('Madhya Pradesh', 'Madhya Pradesh')], max_length=30),
        ),
    ]
