# Generated by Django 6.0.7 on 2026-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
