# Generated by Django 6.0.7 on 2026-08-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
